<?php
$pageTitle = "Common UNIX commands?";
$path = "../";
include($path . "inc/navbar.php");

?>

    <main class="tutorialsMain">
        <h1>Commands for Unix Files</h1>
        <section>
            <p>The Unix file structure is hierarchical and starts with the root directory ("/"), from which all other directories and files stem. Here's an overview of key directories:</p>
            <ul>
                <li><strong>/bin:</strong> Essential user binaries reside here, containing fundamental command-line utilities like ls, cp, mv, and rm.
                    <div class="code">Example: <code>ls /bin</code></div>
                </li>
                <li><strong>/sbin:</strong> Similar to /bin, but it holds binaries primarily used by system administrators for system maintenance and repair.
                    <div class="code">Example: <code>ls /sbin</code></div>
                </li>
                <li><strong>/etc:</strong> Configuration files for the system and various applications are stored here. This directory contains crucial system-wide configurations like network settings, user authentication, and startup scripts.
                    <div class="code">Example: <code>ls /etc</code></div>
                </li>
                <li><strong>/usr:</strong> This directory contains user-related programs, libraries, documentation, and other files not essential for the system's basic operation. Subdirectories include /usr/bin for user binaries, /usr/sbin for system administration binaries, /usr/lib for libraries, and /usr/include for header files.
                    <div class="code">Example: <code>ls /usr</code></div>
                </li>
                <li><strong>/lib:</strong> Essential shared libraries necessary for booting and running programs are stored here.
                    <div class="code">Example: <code>ls /lib</code></div>
                </li>
                <li><strong>/var:</strong> Variable data, such as logs, spool files, and temporary files generated by processes, are kept here. Subdirectories include /var/log for system logs and /var/spool for print queues and mail.
                    <div class="code">Example: <code>ls /var</code></div>
                </li>
                <li><strong>/tmp:</strong> Temporary files that are typically cleared upon system reboot are stored here. Users and programs can write temporary data to this directory.
                    <div class="code">Example: <code>ls /tmp</code></div>
                </li>
                <li><strong>/dev:</strong> Device files representing physical and virtual devices are located here.
                    <div class="code">Example: <code>ls /dev</code></div>
                </li>
                <li><strong>/home:</strong> User home directories are usually found here.
                    <div class="code">Example: <code>ls /home</code></div>
                </li>
                <li><strong>/root:</strong> The home directory for the root user, which has full administrative privileges.
                    <div class="code">Example: <code>ls /root</code></div>
                </li>
                <li><strong>/boot:</strong> Contains files required for booting the operating system.
                    <div class="code">Example: <code>ls /boot</code></div>
                </li>
                <li><strong>/opt:</strong> Optional software packages can be installed in this directory.
                    <div class="code">Example: <code>ls /opt</code></div>
                </li>
                <li><strong>/. :</strong> Current directory that the terminal is working in.
                    <div class="code">Example: <code>ls .</code></div>
                </li>
                <li><strong>/.. :</strong> Parent directory of the current working directory.
                    <div class="code">Example: <code>ls ..</code></div>
                </li>
            </ul>
        </section>
        <a href="text_editors.php"><button>Next: Text Editors</button></a>
    </main>

<?php

    include($path . "inc/footer.php");

?>